my_string = (input("Напишите что нибудь: "))
string = len(my_string)
print("Количество символов в вашей строке: ", string)
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(" ", ""))
print(my_string[0])
print(my_string[-1])
